abstract:     VMware vCloud API
installdirs:  site
license:      perl
name:         VMware-vCloud
version:      1.4
version_from: lib/VMware/vCloud.pm

requires:
  Data::Dumper: 0
  LWP: 0
  XML::Simple: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
