abstract:     VMware vCloud API
installdirs:  site
license:      perl
name:         VMware-vCloud
version:      1.1
version_from: lib/VMware/vCloud.pm

requires:
  LWP: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
